--------------------------------------------------------------------------------
--- Generated exports map for dsl-fsm/
-- @module dsl-fsm.code.exports
-- This file is a part of le-dsl-fsm project
-- Copyright (c) LogicEditor <info@logiceditor.com>
-- Copyright (c) le-dsl-fsm authors
-- See file `COPYRIGHT` for the license.
--------------------------------------------------------------------------------
-- WARNING! Do not change manually!
--          Generated by list-exports.
--------------------------------------------------------------------------------

return
{
  allow_any_dsl_namespace =
  {
    { "dsl-fsm/common_env.lua", w = 0 };
  };
  check_dsl_fsm =
  {
    { "dsl-fsm/check.lua", w = 0 };
  };
  check_dsl_fsm_handler_chunk =
  {
    { "dsl-fsm/check.lua", w = 0 };
  };
  create_dsl_env_mt =
  {
    { "dsl-fsm/common_env.lua", w = 0 };
  };
  do_in_common_dsl_environment =
  {
    { "dsl-fsm/common_env.lua", w = 0 };
  };
  dsl_fsm_bootstrap_chunk =
  {
    { "dsl-fsm/bootstrap.lua", w = 0 };
  };
  make_dsl_manager =
  {
    { "dsl-fsm/dsl_manager.lua", w = 0 };
  };
}
